apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ukj55bwhf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ukj55bwhf-python 
  name: ukj55bwhf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ukj55bwhf-python 
